services:
  db:
    image: postgres:15-alpine
    container_name: weather-monitor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Intelligent_Data_Analysis
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/supabase/schema.sql:/docker-entrypoint-initdb.d/init.sql

  pipeline:
    build:
      context: .
      dockerfile: data-pipeline/Dockerfile
    container_name: weather-data-pipeline
    environment:
      - DB_USER=postgres.lzkbkkhhuyvefjqemdtk
      - DB_PASSWORD=Trunghieu06012005
      - DB_HOST=aws-1-ap-northeast-2.pooler.supabase.com
      - DB_PORT=6543
      - DB_NAME=postgres
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  pgdata:

